QuickNote/Controllers/CategoryController.cs
using Microsoft.AspNet.Identity;
using QuickNote.Data;
using QuickNote.Data.Tables;
using QuickNote.Models.CategoryModels;
using QuickNote.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuickCategory.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            CategoryService service = CreateCategoryService();
            var model = service.GetAllCategories();

            return View(model);
        }

        //GET: CategoryCreate
        public ActionResult Create()
        {
            return View();
        }

        //POST: Category
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateCategoryService();

            if (service.CreateCategory(model))
            {
                TempData["SaveResult"] = "Your note was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Category could not be created.");

            return View(model);
        }

        //GET: CategoryDetail
        [HttpGet]

        public ActionResult Details(int id)
        {
            var svc = CreateCategoryService();
            var model = svc.GetCategoryById(id);

            
   ////***extra code for NotesInThisCategory

   //         //Locate the correct instance of Category
   //         var ctx = new ApplicationDbContext();
   //         var entity =
   //             ctx
   //                 .Categories
   //                 .Single(e => e.CategoryId == id);

   //         //Create a list to hold the data from category.NotesInThisCategory
   //         List<Note> notesInThisCategory = new List<Note>();

   //         //null check
   //         if(notesInThisCategory != null)
   //         {
   //         //Set value of List to the entity's collection of Notes
   //         notesInThisCategory = entity.NotesInThisCategory.ToList();

   //         //Create ViewBag so that the data can be passed to the view
   //         ViewBag.NotesInThisCategory = notesInThisCategory;
   //         }

            return View(model);
        }

        //GET: CategoryUpdate
        [HttpGet]

        public ActionResult Edit(int id)
        {
            var service = CreateCategoryService();
            var detail = service.GetCategoryById(id);
            var model =
                new CategoryEdit
                {
                    CategoryId = detail.CategoryId,
                    CategoryName = detail.CategoryName,

                };
            return View(model);
        }

        //POST:CategoryEdit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CategoryEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.CategoryId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateCategoryService();

            if (service.UpdateCategory(model, id))
            {
                TempData["SaveResult"] = "Your note was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your note could not be updated.");
            return View(model);
        }

        //GET:DeleteCategory
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateCategoryService();
            var model = svc.GetCategoryById(id);

            return View(model);
        }

        //POST:Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateCategoryService();

            service.DeleteCategory(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");
        }


        //Helper method(s)
        private CategoryService CreateCategoryService()
        {

            var service = new CategoryService();
            return service;
        }
    }
}

QuickNote/Controllers/NoteController.cs
using Microsoft.AspNet.Identity;
using QuickNote.Data;
using QuickNote.Data.Tables;
using QuickNote.Models.NoteModels;
using QuickNote.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuickNote.Controllers
{
    [Authorize]
    public class NoteController : Controller
    {
        // GET: Note
        public ActionResult Index()
        {
            NoteService service = CreateNoteService();
            var model = service.GetAllNotes();
            
            
            

            return View(model);
        }

        //GET: NoteCreate
        public ActionResult Create()
        {
            //iterating through the Categories DbSet, and adding the category Names to a list
            
            var svc = CreateNoteService();

            ViewBag.Categories =svc.GetCategories();
            return View();
        }

        //POST: Note
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NoteCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateNoteService();

            if (service.CreateNote(model))
            {
                TempData["SaveResult"] = "Your note was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Note could not be created.");

            return View(model);
        }

        //GET: NoteDetail
        [HttpGet]
        
        public ActionResult Details(int id)
        {
            var svc = CreateNoteService();
            var model = svc.GetNoteById(id);
            return View(model);
        }

        //GET: NoteUpdate
        [HttpGet]
        
        public ActionResult Edit(int id)
        {
            var service = CreateNoteService();
            var detail = service.GetNoteById(id);
            
            //iterating through the Categories DbSet, and adding the category Names to a list
            var ctx = new ApplicationDbContext();

            

            ViewBag.Categories = service.GetCategories();

            var model =
                new NoteEdit
                {
                    NoteId = detail.NoteId,
                    Title = detail.Title,
                    Content = detail.Content,
                    CategoryId = detail.CategoryId,
                    ModifiedUtc= detail.ModifiedUtc
                };
            return View(model);
        }

        //POST:NoteEdit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, NoteEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.NoteId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateNoteService();

            if (service.UpdateNote(model))
            {
                TempData["SaveResult"] = "Your note was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your note could not be updated.");
            return View(model);
        }

        //GET:DeleteNote
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateNoteService();
            var model = svc.GetNoteById(id);

            return View(model);
        }

        //POST:Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateNoteService();

            service.DeleteNote(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");
        }


        //Helper method(s)
        private NoteService CreateNoteService()
        {
            var userId = User.Identity.GetUserId();
            var service = new NoteService(userId);
            return service;
        }
    }
}

QuickNote/Views/Shared/_Dashboard.cshtml
<h1 id="titleText">
    Welcome Back!
</h1>

QuickNote/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Quick-Note</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body class="text-white">
    <div class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container">
            @Html.ActionLink("Quick-Note", "Index", "Home", new { area = "" }, htmlAttributes: new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-expanded="true">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse ">
                <ul class="navbar-nav list-inline mr-auto ">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, htmlAttributes: new { @class = "nav-link" })</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">@Html.ActionLink("Notes", "Index", "Note", null, htmlAttributes: new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Categories", "Index", "Category", null, htmlAttributes: new { @class = "nav-link" })</li>
                    }
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", null, htmlAttributes: new { @class = "nav-link" })</li>
                </ul>


                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()


    </div>
    <footer class="text-center ">
        <hr />
        <p>&copy; @DateTime.Now.Year - Quick-Note</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/Bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>

QuickNote/Views/Shared/_NoteIndexPartial.cshtml
@model QuickNote.Models.NoteModels.NoteListItem